name: architecture_demo
description: A Flutter application to demo scalable architecture.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  persist_theme: ^1.5.1
  cupertino_icons: ^0.1.2
  meta: ^1.1.6
  equatable: ^0.3.0
  shared_preferences: ^0.5.3+4
  injector: ^1.0.8
  bloc: ^0.14.4
  flutter_bloc: 0.20.0
  provider: ^3.0.0+1
  flutter_statusbarcolor: 0.2.1
  query_params: ^0.6.1
  dio: ^2.1.13
  jaguar_serializer:
  cached_network_image: ^1.1.1

transformers:
- dartson

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  jaguar_serializer_cli:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/pixabay_logo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
